name: Build and Deploy Site
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest

    steps:
    - name: install dependencies
      run: |
       zypper refresh
       zypper --non-interactive update
       zypper --non-interactive install git libxslt linkchecker lowdown make python3 sblg nodejs npm
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: build site
      run: make
    - name: package site
      run: |
       mkdir site
       make install PREFIX=$(pwd)/site
    - name: check for broken links
      run: |
        python3 -m http.server -d site 8000 > server.log &
        sleep 10
        linkchecker -o Failures --check-extern http://0.0.0.0:8000/ || true
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
       path: site

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
